/**
 * Add women's local perfumes (type='local', category='women')
 * Run: node database/replace-women.js
 */
const Database = require('better-sqlite3');
const path     = require('path');

const db = new Database(path.join(__dirname, '../data/store.db'));

const DEMO_PRICE = 50000; // 50,000 LBP

const WOMEN = [
  // A
  { n: "5th Avenue",                                  brand: "Elizabeth Arden" },
  { n: "Addict Dior",                                 brand: "Dior" },
  { n: "Açkim",                                       brand: "Other" },
  { n: "Alien",                                       brand: "Thierry Mugler" },
  { n: "Alien Oud",                                   brand: "Thierry Mugler" },
  { n: "Alien Premium",                               brand: "Thierry Mugler" },
  { n: "Amarige",                                     brand: "Givenchy" },
  { n: "Amirat Al Arab",                              brand: "Asdaaf" },
  { n: "Amor Amor",                                   brand: "Cacharel" },
  { n: "Amouage",                                     brand: "Amouage" },
  { n: "Amouage Honor",                               brand: "Amouage" },
  { n: "Amouage Love Delight",                        brand: "Amouage" },
  { n: "Anais",                                       brand: "Cacharel" },
  { n: "Angel",                                       brand: "Thierry Mugler" },
  { n: "Angel Fantasm Mugler",                        brand: "Thierry Mugler" },
  { n: "Aoud Queen Roses",                            brand: "Montale" },
  { n: "Aqua Gio",                                    brand: "Giorgio Armani" },
  { n: "Armani Code",                                 brand: "Giorgio Armani" },
  { n: "Attrape-Rêves",                               brand: "Louis Vuitton" },
  { n: "Amyris Femme",                                brand: "Other" },
  // B
  { n: "Because It's You",                            brand: "Giorgio Armani" },
  { n: "Bvlgari Woman",                               brand: "Bvlgari" },
  { n: "Black Opium",                                 brand: "Yves Saint Laurent" },
  { n: "Black Opium Over Red",                        brand: "Yves Saint Laurent" },
  { n: "Black XS",                                    brand: "Paco Rabanne" },
  { n: "Blue Lady",                                   brand: "Other" },
  { n: "Bombshell",                                   brand: "Victoria's Secret" },
  { n: "Bombshell Intense",                           brand: "Victoria's Secret" },
  { n: "Britney Spears",                              brand: "Britney Spears" },
  { n: "Burberry",                                    brand: "Burberry" },
  { n: "Burberry Body",                               brand: "Burberry" },
  { n: "Burberry Brit",                               brand: "Burberry" },
  { n: "Burberry Goddess",                            brand: "Burberry" },
  { n: "Burberry Her",                                brand: "Burberry" },
  { n: "Burberry Her Elixir",                         brand: "Burberry" },
  { n: "Burberry London",                             brand: "Burberry" },
  { n: "Burberry Sport",                              brand: "Burberry" },
  { n: "Burberry The Beat",                           brand: "Burberry" },
  { n: "Burberry Weekend",                            brand: "Burberry" },
  // C
  { n: "Cacharel",                                    brand: "Cacharel" },
  { n: "Cacharel Noa",                                brand: "Cacharel" },
  { n: "Can't Stop Loving You",                       brand: "By Kilian" },
  { n: "Carolina Herrera CH",                         brand: "Carolina Herrera" },
  { n: "Chanel Chance",                               brand: "Chanel" },
  { n: "Chanel Chance Eau Fraîche",                   brand: "Chanel" },
  { n: "Chanel Chance Eau Tendre",                    brand: "Chanel" },
  { n: "Chanel Chance Eau Vive",                      brand: "Chanel" },
  { n: "Chanel Chance Eau Splendide",                 brand: "Chanel" },
  { n: "Chanel Coco",                                 brand: "Chanel" },
  { n: "Chanel Coco Mademoiselle",                    brand: "Chanel" },
  { n: "Chanel Coco Noir",                            brand: "Chanel" },
  { n: "Chanel No. 5",                                brand: "Chanel" },
  { n: "Chanel No. 19",                               brand: "Chanel" },
  { n: "Charlie",                                     brand: "Revlon" },
  { n: "Chloé",                                       brand: "Chloé" },
  { n: "Chloé Nomade",                                brand: "Chloé" },
  { n: "Cloud Pink",                                  brand: "Other" },
  { n: "Coco Vanille",                                brand: "Other" },
  { n: "Cool Water",                                  brand: "Davidoff" },
  { n: "Creed Carmina",                               brand: "Creed" },
  { n: "Creed Eladaria",                              brand: "Creed" },
  { n: "CK One N2U",                                  brand: "Calvin Klein" },
  // D
  { n: "Dalaa Al Banat",                              brand: "Other" },
  { n: "Dalaa Al Sabaya",                             brand: "Other" },
  { n: "Darej",                                       brand: "Rasasi" },
  { n: "Davidoff",                                    brand: "Davidoff" },
  { n: "Delina",                                      brand: "Parfums de Marly" },
  { n: "Delina Exclusif",                             brand: "Parfums de Marly" },
  { n: "Divine",                                      brand: "Jean Paul Gaultier" },
  { n: "Dolce & Gabbana",                             brand: "Dolce & Gabbana" },
  { n: "Dolce & Gabbana Devotion Intense",            brand: "Dolce & Gabbana" },
  { n: "Dolce & Gabbana Intense",                     brand: "Dolce & Gabbana" },
  { n: "Dolce & Gabbana L'Imperatrice",               brand: "Dolce & Gabbana" },
  { n: "Dolce & Gabbana Only The One",                brand: "Dolce & Gabbana" },
  { n: "Dolce & Gabbana The One",                     brand: "Dolce & Gabbana" },
  { n: "Dolce & Gabbana The One Royal Night",         brand: "Dolce & Gabbana" },
  { n: "Dolce Vita",                                  brand: "Dior" },
  // E
  { n: "Eau Demoiselle Bois de Oud",                  brand: "Guerlain" },
  { n: "Eclat d'Arpège",                              brand: "Lanvin" },
  { n: "Eclaire",                                     brand: "Lattafa" },
  { n: "Eghraa",                                      brand: "Other" },
  { n: "Eilish",                                      brand: "Billie Eilish" },
  { n: "Elie Saab",                                   brand: "Elie Saab" },
  { n: "Elie Saab Elixir",                            brand: "Elie Saab" },
  { n: "Elie Saab Le Parfum",                         brand: "Elie Saab" },
  { n: "Elie Saab Le Parfum Essential",               brand: "Elie Saab" },
  { n: "Elie Saab Le Parfum In White",                brand: "Elie Saab" },
  { n: "Elie Saab Royal",                             brand: "Elie Saab" },
  { n: "Elle",                                        brand: "Yves Saint Laurent" },
  { n: "Emotion Rasasi",                              brand: "Rasasi" },
  { n: "Escada Bali Paradise",                        brand: "Escada" },
  { n: "Escada Born in Paradise",                     brand: "Escada" },
  { n: "Escada Cherry",                               brand: "Escada" },
  { n: "Escada Collection",                           brand: "Escada" },
  { n: "Escada Especially",                           brand: "Escada" },
  { n: "Escada Magnetism",                            brand: "Escada" },
  { n: "Escada Moon Sparkle",                         brand: "Escada" },
  { n: "Escada Rockin Rio",                           brand: "Escada" },
  { n: "Escada Taj",                                  brand: "Escada" },
  { n: "Estée Lauder",                                brand: "Estée Lauder" },
  { n: "Eternity",                                    brand: "Calvin Klein" },
  { n: "Euphoria",                                    brand: "Calvin Klein" },
  { n: "Escape",                                      brand: "Calvin Klein" },
  // F
  { n: "Fakher Lattafa Rose",                         brand: "Lattafa" },
  { n: "Fam",                                         brand: "Lady Gaga" },
  { n: "Fantasy",                                     brand: "Britney Spears" },
  { n: "Faraway",                                     brand: "Avon" },
  { n: "Fidji",                                       brand: "Guy Laroche" },
  { n: "Fifa Tosca",                                  brand: "Other" },
  { n: "Fogg",                                        brand: "Fogg" },
  { n: "Flowerbomb",                                  brand: "Viktor & Rolf" },
  { n: "Flower Narcotique",                           brand: "Ex Nihilo" },
  // G
  { n: "G Giorgio Beverly Hills",                     brand: "Giorgio Beverly Hills" },
  { n: "Givenchy Irresistible",                       brand: "Givenchy" },
  { n: "Givenchy L'Interdit",                         brand: "Givenchy" },
  { n: "Givenchy L'Interdit Absolute",                brand: "Givenchy" },
  { n: "Givenchy L'Interdit Rouge",                   brand: "Givenchy" },
  { n: "Givenchy L'Interdit Tubéreuse Noire",         brand: "Givenchy" },
  { n: "Gissah One & Only",                           brand: "Gissah" },
  { n: "Gris Dior",                                   brand: "Dior" },
  { n: "Gris Montaigne",                              brand: "Dior" },
  { n: "Gucci Bloom",                                 brand: "Gucci" },
  { n: "Gucci Bamboo",                                brand: "Gucci" },
  { n: "Gucci by Gucci",                              brand: "Gucci" },
  { n: "Gucci Envy Me",                               brand: "Gucci" },
  { n: "Gucci Flora",                                 brand: "Gucci" },
  { n: "Gucci Flora Gorgeous Gardenia",               brand: "Gucci" },
  { n: "Gucci Flora Gorgeous Magnolia",               brand: "Gucci" },
  { n: "Gucci Flora Gorgeous Orchid",                 brand: "Gucci" },
  { n: "Gucci Guilty",                                brand: "Gucci" },
  { n: "Gucci Premiere",                              brand: "Gucci" },
  { n: "Gucci Rush",                                  brand: "Gucci" },
  // H
  { n: "Harim Al Sultan",                             brand: "Ard Al Zaafaran" },
  { n: "Hawaii",                                      brand: "Other" },
  { n: "Hot Sex",                                     brand: "Other" },
  { n: "Hugo Woman",                                  brand: "Hugo Boss" },
  { n: "Hypnose Senses",                              brand: "Lancôme" },
  { n: "Hypnotic Poison",                             brand: "Dior" },
  // I
  { n: "Idôle",                                       brand: "Lancôme" },
  { n: "Idôle Aura",                                  brand: "Lancôme" },
  // J
  { n: "J'adore",                                     brand: "Dior" },
  { n: "Jovan Musk",                                  brand: "Jovan" },
  { n: "Just Cavalli",                                brand: "Roberto Cavalli" },
  // K
  { n: "Kashkha",                                     brand: "Other" },
  { n: "Kayali 14 Capri Lemon Sugar",                 brand: "Kayali" },
  { n: "Kayali 20 Maldives Ylang",                    brand: "Kayali" },
  { n: "Kayali 36 Wedding Silk Santal",               brand: "Kayali" },
  { n: "Kayali 39 Eden Sparkling Lychee",             brand: "Kayali" },
  { n: "Kayali 42 Vanilla Candy Rock Sugar",          brand: "Kayali" },
  { n: "Kayali 81 Yum Boujee Marshmallow",            brand: "Kayali" },
  { n: "Kayali Fleur Majesty Rose Royale",            brand: "Kayali" },
  { n: "Kenzo Amour",                                 brand: "Kenzo" },
  { n: "Kenzo Flower",                                brand: "Kenzo" },
  { n: "Kenzo",                                       brand: "Kenzo" },
  { n: "Kobra",                                       brand: "Lattafa" },
  // L
  { n: "La Belle",                                    brand: "Jean Paul Gaultier" },
  { n: "La Belle Paradise Garden",                    brand: "Jean Paul Gaultier" },
  { n: "La Bomba",                                    brand: "Carolina Herrera" },
  { n: "La Nuit Trésor",                              brand: "Lancôme" },
  { n: "La Nuit Trésor À La Folie",                   brand: "Lancôme" },
  { n: "La Nuit Trésor Vanille Noire",                brand: "Lancôme" },
  { n: "La Petite Robe Noire",                        brand: "Guerlain" },
  { n: "La Tosca",                                    brand: "Xerjoff" },
  { n: "La Vie Est Belle",                            brand: "Lancôme" },
  { n: "La Vie Est Belle Elixir",                     brand: "Lancôme" },
  { n: "La Vie Est Belle Rose",                       brand: "Lancôme" },
  { n: "La Vie Est Belle Rose Extraordinaire",        brand: "Lancôme" },
  { n: "Lacoste Touch of Pink",                       brand: "Lacoste" },
  { n: "Lady Million",                                brand: "Paco Rabanne" },
  { n: "Lamsat",                                      brand: "Other" },
  { n: "Lancôme Trésor",                              brand: "Lancôme" },
  { n: "L'Instant de Guerlain",                       brand: "Guerlain" },
  { n: "Libre",                                       brand: "Yves Saint Laurent" },
  { n: "Libre Intense",                               brand: "Yves Saint Laurent" },
  { n: "Libre Le Parfum",                             brand: "Yves Saint Laurent" },
  { n: "Libre Vanille Couture",                       brand: "Yves Saint Laurent" },
  { n: "Libre Flames",                                brand: "Yves Saint Laurent" },
  { n: "Light Blue",                                  brand: "Dolce & Gabbana" },
  { n: "Lili",                                        brand: "Other" },
  { n: "Lira",                                        brand: "Xerjoff" },
  { n: "Lolita Lempicka",                             brand: "Lolita Lempicka" },
  { n: "Love Addict",                                 brand: "Victoria's Secret" },
  { n: "Love Don't Be Shy",                           brand: "By Kilian" },
  { n: "Love Is Heavenly",                            brand: "Victoria's Secret" },
  { n: "Loverdose",                                   brand: "Diesel" },
  // M
  { n: "Madame Rochas",                               brand: "Rochas" },
  { n: "Madawi",                                      brand: "Arabian Oud" },
  { n: "Malizia",                                     brand: "Malizia" },
  { n: "Manifesto",                                   brand: "Yves Saint Laurent" },
  { n: "Marry Me",                                    brand: "Lanvin" },
  { n: "Maui in a Bottle Sweet Banana",               brand: "Kayali" },
  { n: "Mayyar",                                      brand: "Lattafa" },
  { n: "Mademoiselle Azzaro",                         brand: "Azzaro" },
  { n: "Mikyaj",                                      brand: "Other" },
  { n: "Miss Dior",                                   brand: "Dior" },
  { n: "Miss Dior Blooming",                          brand: "Dior" },
  { n: "Miss Dior Cherry",                            brand: "Dior" },
  { n: "Miracle",                                     brand: "Lancôme" },
  { n: "Mon Guerlain",                                brand: "Guerlain" },
  { n: "Mont Blanc",                                  brand: "Mont Blanc" },
  { n: "My Burberry",                                 brand: "Burberry" },
  { n: "My Burberry Black",                           brand: "Burberry" },
  { n: "My Euphoria",                                 brand: "Calvin Klein" },
  { n: "My Way",                                      brand: "Giorgio Armani" },
  { n: "My Way Intense",                              brand: "Giorgio Armani" },
  { n: "My Way Parfum",                               brand: "Giorgio Armani" },
  { n: "My Way Ylang",                                brand: "Giorgio Armani" },
  // N
  { n: "Narciso Rodriguez Amber Musk",                brand: "Narciso Rodriguez" },
  { n: "Narciso Rodriguez Fleur Musk",                brand: "Narciso Rodriguez" },
  { n: "Narciso Rodriguez For Her",                   brand: "Narciso Rodriguez" },
  { n: "Narciso Rodriguez Musc Noir Rose",            brand: "Narciso Rodriguez" },
  { n: "Narciso Rodriguez Musc Nude",                 brand: "Narciso Rodriguez" },
  { n: "Narciso Rodriguez Pure Musc",                 brand: "Narciso Rodriguez" },
  { n: "Narciso Rodriguez Safran Musk",               brand: "Narciso Rodriguez" },
  { n: "Narciso Rouge",                               brand: "Narciso Rodriguez" },
  { n: "Narciso Powder",                              brand: "Narciso Rodriguez" },
  { n: "Nina Ricci",                                  brand: "Nina Ricci" },
  { n: "Nina Ricci Premier Jour",                     brand: "Nina Ricci" },
  { n: "Nina Ricci Vénus",                            brand: "Nina Ricci" },
  // O
  { n: "Olympea",                                     brand: "Paco Rabanne" },
  { n: "Omnia Amethyste",                             brand: "Bvlgari" },
  { n: "Organza",                                     brand: "Givenchy" },
  // P
  { n: "Paco Rabanne",                                brand: "Paco Rabanne" },
  { n: "Paris",                                       brand: "Yves Saint Laurent" },
  { n: "Parisienne L'Extreme",                        brand: "Yves Saint Laurent" },
  { n: "Paris Hilton",                                brand: "Paris Hilton" },
  { n: "Pink Sugar Lollipink",                        brand: "Aquolina" },
  { n: "Pleasures",                                   brand: "Estée Lauder" },
  { n: "Poison",                                      brand: "Dior" },
  { n: "Poison Girl",                                 brand: "Dior" },
  { n: "Poison Pure",                                 brand: "Dior" },
  { n: "Prada Candy",                                 brand: "Prada" },
  { n: "Prada Candy Gloss",                           brand: "Prada" },
  { n: "Prada Paradoxe",                              brand: "Prada" },
  { n: "Prada Paradoxe Intense",                      brand: "Prada" },
  { n: "Princess",                                    brand: "Lanvin" },
  { n: "Pure Seduction Splash",                       brand: "Victoria's Secret" },
  // Q
  { n: "Queen of Silk",                               brand: "Creed" },
  // R
  { n: "Raghba",                                      brand: "Lattafa" },
  { n: "Ralph Lauren",                                brand: "Ralph Lauren" },
  { n: "Rave Pure Desire Gold",                       brand: "Other" },
  { n: "Red Jeans",                                   brand: "Versace" },
  { n: "Ricci Ricci",                                 brand: "Nina Ricci" },
  { n: "Roberto Cavalli",                             brand: "Roberto Cavalli" },
  { n: "Roberto Cavalli Paradiso",                    brand: "Roberto Cavalli" },
  { n: "Romance",                                     brand: "Ralph Lauren" },
  { n: "Rose Couture",                                brand: "Other" },
  { n: "Rose des Vents",                              brand: "Louis Vuitton" },
  // S
  { n: "Samsara",                                     brand: "Guerlain" },
  { n: "Sandal Wood",                                 brand: "Other" },
  { n: "Scandal",                                     brand: "Jean Paul Gaultier" },
  { n: "Scandalous",                                  brand: "Victoria's Secret" },
  { n: "Si",                                          brand: "Giorgio Armani" },
  { n: "Si Fiori",                                    brand: "Giorgio Armani" },
  { n: "Si Intense",                                  brand: "Giorgio Armani" },
  { n: "Si Passione",                                 brand: "Giorgio Armani" },
  { n: "Si Rose Signature",                           brand: "Giorgio Armani" },
  { n: "Sirène",                                      brand: "Fragrance du Bois" },
  { n: "So Scandal",                                  brand: "Jean Paul Gaultier" },
  { n: "Stella McCartney",                            brand: "Stella McCartney" },
  { n: "Sweet Lolita Lempicka",                       brand: "Lolita Lempicka" },
  // T
  { n: "Tender Poison",                               brand: "Dior" },
  { n: "Today",                                       brand: "Other" },
  { n: "Tom Ford Noir",                               brand: "Tom Ford" },
  { n: "Tom Ford Orchid Soleil",                      brand: "Tom Ford" },
  { n: "Tom Ford Rose",                               brand: "Tom Ford" },
  { n: "Tom Ford Velvet Orchid",                      brand: "Tom Ford" },
  { n: "Tomorrow",                                    brand: "Other" },
  { n: "Touch of Beauty",                             brand: "Other" },
  { n: "Trésor",                                      brand: "Lancôme" },
  { n: "Trésor In Love",                              brand: "Lancôme" },
  { n: "Trésor Midnight Rose",                        brand: "Lancôme" },
  { n: "Twilly d'Hermès",                             brand: "Hermès" },
  // U
  { n: "Ultra Violet",                                brand: "Paco Rabanne" },
  // V
  { n: "Valentino",                                   brand: "Valentino" },
  { n: "Valentino Donna",                             brand: "Valentino" },
  { n: "Valentino Donna Born in Roma",                brand: "Valentino" },
  { n: "Valentino Donna Born in Roma Green Stravaganza", brand: "Valentino" },
  { n: "Valentino Donna Born in Roma Intense",        brand: "Valentino" },
  { n: "Valentino Voce Viva",                         brand: "Valentino" },
  { n: "Versace",                                     brand: "Versace" },
  { n: "Versace Bright Crystal",                      brand: "Versace" },
  { n: "Versace Eros",                                brand: "Versace" },
  { n: "Versace Noir",                                brand: "Versace" },
  { n: "Versace Red Jeans",                           brand: "Versace" },
  { n: "Very Irresistible",                           brand: "Givenchy" },
  { n: "Very Sexy",                                   brand: "Victoria's Secret" },
  { n: "Very Sexy New",                               brand: "Victoria's Secret" },
  { n: "VIP 212",                                     brand: "Carolina Herrera" },
  { n: "VIP 212 Rose",                                brand: "Carolina Herrera" },
  { n: "VIP Private Show",                            brand: "Britney Spears" },
  { n: "Viva La Juicy",                               brand: "Juicy Couture" },
  // W
  { n: "Wanted Girl",                                 brand: "Azzaro" },
  { n: "Washwasha",                                   brand: "Lattafa" },
  { n: "Wild Blue",                                   brand: "Jo Malone" },
  // Y
  { n: "Yara",                                        brand: "Lattafa" },
  { n: "Yara Candy",                                  brand: "Lattafa" },
  { n: "Yara Moi",                                    brand: "Lattafa" },
  { n: "Yara Orange",                                 brand: "Lattafa" },
  { n: "Yes I Am",                                    brand: "Cacharel" },
  // Z
  { n: "Zara",                                        brand: "Zara" },
  { n: "Zara Orchid",                                 brand: "Zara" },
  { n: "Zara Oriental",                               brand: "Zara" },
  { n: "Zelda",                                       brand: "Other" },
];

const khaleejiSet = new Set(['Lattafa', 'Rasasi', 'Arabian Oud', 'Ajmal', 'Asdaaf', 'Ard Al Zaafaran']);

const insertBrand   = db.prepare("INSERT OR IGNORE INTO brands (name, type) VALUES (?, ?)");
const insertProduct = db.prepare(`
  INSERT INTO products (name_en, category, brand, price, in_stock, featured, type)
  VALUES (?, 'women', ?, ?, 1, 0, 'local')
`);

console.log('Adding women\'s products...');

const run = db.transaction(() => {
  // Remove old local women's products
  const del = db.prepare("DELETE FROM products WHERE category='women' AND type='local'").run();
  console.log(`  ✓ Removed ${del.changes} old women's products`);

  // Ensure brands
  const brandsSeen = new Set(WOMEN.map(p => p.brand));
  for (const b of brandsSeen) {
    insertBrand.run(b, khaleejiSet.has(b) ? 'khaleeji' : 'western');
  }

  // Insert products
  for (const p of WOMEN) insertProduct.run(p.n, p.brand, DEMO_PRICE);
  console.log(`  ✓ Inserted ${WOMEN.length} women's products`);
  console.log(`  ✓ Demo price: ${DEMO_PRICE.toLocaleString()} LBP`);
});

run();
console.log('\n✅ Done! Open http://localhost:3000/shop?category=women to verify.');
